.catalog:
  name: Plex Server
  version: v0.1
  description: Plex Media Server
  questions:
    - variable: "hostname"
      description: "Hostname of the server."
      label: "Hostname:"
      required: true
      default: "media1"
      type: "string"
    - variable: "domain"
      description: "Domain of media service."
      label: "Domain:"
      required: true
      default: "rm.lan"
      type: "string"
    - variable: "host_label"
      description: "Host label where to run NFS service."
      label: "Host label:"
      required: true
      default: "media-stack=true"
      type: "string"
    - variable: "PATHMEDIA"
      type: "string"
      label: "Media Path"
      description: the Path to your library (/media, or a nfs mount /mnt, ...)
      default: '/media'
    - variable: "PLEX_PORT"
      type: "string"
      label: "Plex Port"
      description: Frontend Port of Plex
      default: 32400
    - variable: NET
      description: "select Network type"
      label: "Network"
      type: enum
      options:
        - host
        - managed
        - none
      required: true
      default: "host"
    - variable: "plex_ext_ip"
      description: "External IP of Plex"
      label: "External IP:"
      required: false
      default: "10.0.25.201"
      type: "string"
plex:
  scale: 1

plex-ext:
  external_ips:
  - ${plex_ext_ip}